dynamic categorydata = [
  {
    "text":"Burger",
    "image":"Images/burger.jpg"
  },
  {
    "text":"Pizza",
    "image":"Images/pizza.jpg"
  },
  {
    "text":"Chicken",
    "image":"Images/chicken.jpg"
  },
  {
    "text":"Sushi",
    "image":"Images/sushi.jpg"
  },
  {
    "text":"Biryani",
    "image":"Images/biryani.jpg"
  },
  {
    "text":"Karahi",
    "image":"Images/karahi.jpg"
  },
];